<?php
/**
 * Implements hook_menu().
 */
function pizza_menu() {
  //Add item to main menu
  $items['order-pizza'] = array(
    'title' => 'Заказать пицу',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pizza_order_form'),
	'menu_name' => 'main-menu',
	'access callback' => TRUE,
	'type' => MENU_NORMAL_ITEM,
   );
   
   //Add section to configuration page
   $items['admin/config/pizza-region'] = array(
    'title' => 'Pizza and Rgion configuration section',
    'description' => 'This is the parent item',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
	//'file' => 'pizza.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  //Pizza confifguration page
  $items['admin/config/pizza-region/pizza'] = array(
    'title' => 'Administer pizza',
    'description' => 'Add/Edit/Delete Pizza',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('pizza_list_form'),
    'access arguments' => array('administer pizza settings'),
	'file' => 'pizza.admin.inc',
    'type' => MENU_NORMAL_ITEM,
   );

  $items['admin/config/pizza-region/pizza/all'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
	'file' => 'pizza.admin.inc',
  );

  $items['admin/config/pizza-region/pizza/add'] = array(
    'title' => 'Add new pizza',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
	'page arguments' => array('pizza_add_form'),
    'access arguments' => array('administer pizza settings'),
	'file' => 'pizza.admin.inc',
  );
  
  //Region confifguration page
  $items['admin/config/pizza-region/region'] = array(
    'title' => 'Administer regions',
    'description' => 'Add/Edit/Delete Region',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('pizza_region_form'),
    'access arguments' => array('administer region settings'),
	'file' => 'pizza.admin.inc',
    'type' => MENU_NORMAL_ITEM,
   );

  $items['admin/config/pizza-region/region/all'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
	'file' => 'pizza.admin.inc',
  );

  $items['admin/config/pizza-region/region/add'] = array(
    'title' => 'Add new Region',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
	'page arguments' => array('pizza_regionadd_form'),
    'access arguments' => array('administer region settings'),
	'file' => 'pizza.admin.inc',
  );
  
  $items['order-pizza/calc-price'] = array(
    'title' => 'Calc total price',
    'type' => MENU_SUGGESTED_ITEM,
    'page callback' => 'pizza_calc_total_price',
	//'page arguments' => array('pizza_regionadd_form')
  );
   
  return $items;
}

function pizza_order_form($form, &$form_state){
  $form = array();
  
   $pizza_query = db_select('pizza_type', 'pt')
    ->fields('pt', array('pid', 'piza_name', 'piza_price'))
      ->execute();
  
  $region_query = db_select('pizza_region', 'pr')
    ->fields('pr', array('rid', 'region_name', 'region_delivery_price'))
      ->execute();
	  
  $pizza_name = array();
  while($piza_record = $pizza_query->fetchAssoc()) {
	//$pid[] = $piza_record['pid'];
	$pizza_name[] = $piza_record['piza_name'];
	//$pizza_price[] = $piza_record['piza_price'];
  }
  
  $region_name = array();
  while($region_record = $region_query->fetchAssoc()) {
	//$rid[] = $region_record['rid'];
	$region_name[] = $region_record['region_name'];
	//$region_price[] = $region_record['region_delivery_price'];
  }
  
  $type['select'] = array('#input' => TRUE, '#process' => array('expand_radios'));

  $form['pizza_name'] = array(
    '#type' => 'radios',
    '#title' => t('Select Pizza'),
    '#options' => $pizza_name,
    '#description' => t('Select pizza.'),
   );
   
  $quantity = array(
    0 => 1,
    1 => 2,
    2 => 3,
    3 => 4,
    4 => 5,
    5 => 6,
    6 => 7,
    7 => 8,
    8 => 9,
    9 => 10,
    );
   $form['pizza_q'] = array(
    '#type' => 'select',
    '#title' => t('Quantity'),
    '#options' => $quantity,
    '#description' => t('Select quantity.'),
   );
   
  $form['region']   = array(
    '#type'         => 'select',
    '#title'        => t('Region'),
    '#options'      => $region_name,
    '#description'  => t('Select region.'),
   );
   
   $form['jname'] = array(
    '#title'    => 'Pizza name',
	'#type'     => 'textfield',
	'#required' => TRUE,
  );
   
  $form['submit'] = array(
    '#type'       => 'submit',
    '#value'      => t('Order pizza')
  );
  
  return $form;
}


function pizza_order_form_submit($form, $form_state){
  $pizza_name = $form['pizza_name']['#options'][$form_state['values']['pizza_name']];
  
  // Note: select pizza price by pizza name
  $query_single = db_select('pizza_type', 'p')
    ->fields     ('p', array('pid', 'piza_name', 'piza_price'))
    ->condition  ('p.piza_name', $pizza_name)
    ->execute();
  $record    = $query_single->fetchAssoc();
  //drupal_set_message($record['piza_price']);
}